### ISSUE TITLE
字体颜色会串

### ISSUE THREAD

**Issue by 385841539** [smallmarker/TagFlowLayout#1]
根据是否选中 设置背景是ok的， 但是 字体颜色 不  ok。
还有设置单行 时，会有标签 展示一半

**Comment by lfc1101** [comment]
我最近开始使用这个框架，看到您的问题，发现字体颜色是可以根据选中状态而设置改变的。下面是我的代码截图，我用的是kotlin，
![image](https://user-images.githubusercontent.com/33215574/208032654-f2a3ff8d-d430-4fc6-ac31-6f09debe1990.png)
![image](https://user-images.githubusercontent.com/33215574/208032678-ecbbbd1f-cb15-4f97-a318-b99114bb69d3.png)

**Comment by lfc1101** [comment]
> 根据是否选择中设置背景是ok的，但是是字体颜色不ok。 还有设置单行时，会有标签显示半

我最近开始使用这个框架，看到你的问题，发现字体颜色是可以根据选择中状态而设置改变的。下面是我的代码截图，我用的是
kotlin...
![](https://user-images.githubusercontent.com/33215574/208032654-f2a3ff8d-d430-4fc6-ac31-6f09debe1990.png)

![](https://user-images.githubusercontent.com/33215574/208032678-ecbbbd1f-cb15-4f97-a318-b99114bb69d3.png)
